# Generated by Django 6.0.5 on 2026-05-05 21:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('items_seen', models.PositiveIntegerField(default=0)),
                ('items_new', models.PositiveIntegerField(default=0)),
                ('items_updated', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_de', models.CharField(blank=True, max_length=100)),
                ('osm_relation_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('wikidata_id', models.CharField(blank=True, max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='ID ogłoszenia z portalu źródłowego', max_length=255)),
                ('source_portal', models.CharField(max_length=50)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('offer_type', models.CharField(choices=[('rent', 'Wynajem'), ('sale', 'Sprzedaż')], default='rent', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('floor', models.SmallIntegerField(blank=True, null=True)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('has_elevator', models.BooleanField(null=True)),
                ('is_accessible', models.BooleanField(null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('noise_db_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('noise_db_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('suspicious', 'Suspicious'), ('invalid', 'Invalid')], default='valid', max_length=20)),
                ('validation_notes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_seen_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_apartments', to='api.dataversion')),
                ('last_updated_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_apartments', to='api.dataversion')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to='api.district')),
            ],
        ),
        migrations.CreateModel(
            name='EducationFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('facility_type', models.CharField(choices=[('kindergarten', 'Przedszkole'), ('primary', 'Podstawowa'), ('secondary', 'Średnia'), ('university', 'Uczelnia / college'), ('other', 'Inne')], max_length=20)),
                ('raw_amenity', models.CharField(blank=True, max_length=50)),
                ('raw_school_tag', models.CharField(blank=True, max_length=50)),
                ('raw_isced', models.CharField(blank=True, max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_facilities', to='api.district')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_apartments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoiseZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(help_text='OBJECTID z geojson', unique=True)),
                ('min_db', models.PositiveSmallIntegerField()),
                ('max_db', models.PositiveSmallIntegerField()),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['min_db'],
                'indexes': [models.Index(fields=['min_db', 'max_db'], name='api_noisezo_min_db_39a5eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='SafetyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('crimes_total', models.PositiveIntegerField(blank=True, null=True)),
                ('crimes_per_1000', models.DecimalField(decimal_places=3, max_digits=8)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_records', to='api.district')),
            ],
            options={
                'ordering': ['-year', 'district'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('validation_status', models.CharField(max_length=20)),
                ('raw_snapshot', models.JSONField(blank=True, default=dict)),
                ('changed_fields', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.apartment')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.dataversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['apartment', '-created_at'], name='api_apartme_apartme_5a6e17_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['district', 'is_active'], name='api_apartme_distric_d32adf_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['price'], name='api_apartme_price_5323f2_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['validation_status', 'is_active'], name='api_apartme_validat_80d542_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['offer_type', 'is_active'], name='api_apartme_offer_t_973cbf_idx'),
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.UniqueConstraint(fields=('external_id', 'source_portal'), name='uniq_apartment_per_portal'),
        ),
        migrations.AddIndex(
            model_name='educationfacility',
            index=models.Index(fields=['facility_type'], name='api_educati_facilit_b1a4b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='favoriteapartment',
            constraint=models.UniqueConstraint(fields=('user', 'apartment'), name='uniq_user_favorite'),
        ),
        migrations.AddConstraint(
            model_name='safetydata',
            constraint=models.UniqueConstraint(fields=('district', 'year'), name='uniq_safety_per_year'),
        ),
    ]
